# Generated by Django 6.0.2 on 2026-04-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_quoterequest_broker'),
        ('reviews', '0002_alter_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='quote_request',
        ),
        migrations.AddField(
            model_name='review',
            name='broker_quote',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='requests.brokerquote'),
            preserve_default=False,
        ),
    ]
