# Generated by Django 6.0.3 on 2026-04-12 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('requests', '0004_quoterequest_broker'),
        ('reviews', '0003_remove_review_quote_request_review_broker_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='brokers.brokerprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='broker_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.brokerquote'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'broker_quote')},
        ),
    ]
