# Generated by Django 6.0.3 on 2026-04-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('requests', '0003_quickrequesttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brokers.brokerprofile'),
        ),
    ]
